# Generated by Django 5.0.3 on 2024-03-28 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyRecord',
            new_name='Company',
        ),
    ]
