# Generated by Django 5.0.3 on 2024-04-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(blank=True, choices=[('18-24', '18-24'), ('25-34', '25-34'), ('35-44', '35-44'), ('45-54', '45-54'), ('55-64', '55-64'), ('65+', '65+')], max_length=20, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male')], max_length=20, null=True)),
                ('education', models.CharField(blank=True, choices=[('Left School Before 16 years', 'Left School Before 16 years'), ('Left School at 16 years', 'Left School at 16 years'), ('Left School at 17 years', 'Left School at 17 years'), ('Left School at 18 years', 'Left School at 18 years'), ('Some College,No Certificate Or Degree', 'Some College,No Certificate Or Degree'), ('Professional Certificate/ Diploma', 'Professional Certificate/ Diploma'), ('University Degree', 'University Degree'), ('Masters Degree', 'Masters Degree'), ('Doctorate Degree', 'Doctorate Degree')], max_length=100, null=True)),
                ('country', models.CharField(blank=True, choices=[('Australia', 'Australia'), ('Canada', 'Canada'), ('New Zealand', 'New Zealand'), ('Other', 'Other'), ('Republic of Ireland', 'Republic of Ireland'), ('UK', 'UK'), ('USA', 'USA')], max_length=100, null=True)),
                ('ethnicity', models.CharField(blank=True, choices=[('asian', 'asian'), ('black', 'black'), ('mixed-black/asian', 'mixed-black/asian'), ('mixed-white/asian', 'mixed-white/asian'), ('mixed-white/black', 'mixed-white/black'), ('other', 'other'), ('white', 'white')], max_length=100, null=True)),
                ('neuroticism', models.FloatField(blank=True, null=True)),
                ('extraversion', models.FloatField(blank=True, null=True)),
                ('openness_to_experience', models.FloatField(blank=True, null=True)),
                ('agreeableness', models.FloatField(blank=True, null=True)),
                ('conscientiousness', models.FloatField(blank=True, null=True)),
                ('impulsive', models.FloatField(blank=True, null=True)),
                ('sensation_seeking', models.FloatField(blank=True, null=True)),
                ('alcohol', models.CharField(blank=True, choices=[('Never Used', 'Never Used'), ('Used over a Decade Ago', 'Used over a Decade Ago'), ('Used in Last Decade', 'Used in Last Decade'), ('Used in Last Year', 'Used in Last Year'), ('Used in Last Month', 'Used in Last Month'), ('Used in Last Week', 'Used in Last Week'), ('Used in Last Day', 'Used in Last Day')], max_length=100, null=True)),
                ('amphet', models.CharField(blank=True, choices=[('Never Used', 'Never Used'), ('Used over a Decade Ago', 'Used over a Decade Ago'), ('Used in Last Decade', 'Used in Last Decade'), ('Used in Last Year', 'Used in Last Year'), ('Used in Last Month', 'Used in Last Month'), ('Used in Last Week', 'Used in Last Week'), ('Used in Last Day', 'Used in Last Day')], max_length=100, null=True)),
                ('amyl', models.CharField(blank=True, choices=[('Never Used', 'Never Used'), ('Used over a Decade Ago', 'Used over a Decade Ago'), ('Used in Last Decade', 'Used in Last Decade'), ('Used in Last Year', 'Used in Last Year'), ('Used in Last Month', 'Used in Last Month'), ('Used in Last Week', 'Used in Last Week'), ('Used in Last Day', 'Used in Last Day')], max_length=100, null=True)),
                ('benzos', models.CharField(blank=True, choices=[('Never Used', 'Never Used'), ('Used over a Decade Ago', 'Used over a Decade Ago'), ('Used in Last Decade', 'Used in Last Decade'), ('Used in Last Year', 'Used in Last Year'), ('Used in Last Month', 'Used in Last Month'), ('Used in Last Week', 'Used in Last Week'), ('Used in Last Day', 'Used in Last Day')], max_length=100, null=True)),
                ('caff', models.CharField(blank=True, choices=[('Never Used', 'Never Used'), ('Used over a Decade Ago', 'Used over a Decade Ago'), ('Used in Last Decade', 'Used in Last Decade'), ('Used in Last Year', 'Used in Last Year'), ('Used in Last Month', 'Used in Last Month'), ('Used in Last Week', 'Used in Last Week'), ('Used in Last Day', 'Used in Last Day')], max_length=100, null=True)),
                ('cannabis', models.CharField(blank=True, choices=[('Never Used', 'Never Used'), ('Used over a Decade Ago', 'Used over a Decade Ago'), ('Used in Last Decade', 'Used in Last Decade'), ('Used in Last Year', 'Used in Last Year'), ('Used in Last Month', 'Used in Last Month'), ('Used in Last Week', 'Used in Last Week'), ('Used in Last Day', 'Used in Last Day')], max_length=100, null=True)),
                ('choc', models.CharField(blank=True, choices=[('Never Used', 'Never Used'), ('Used over a Decade Ago', 'Used over a Decade Ago'), ('Used in Last Decade', 'Used in Last Decade'), ('Used in Last Year', 'Used in Last Year'), ('Used in Last Month', 'Used in Last Month'), ('Used in Last Week', 'Used in Last Week'), ('Used in Last Day', 'Used in Last Day')], max_length=100, null=True)),
                ('coke', models.CharField(blank=True, choices=[('Never Used', 'Never Used'), ('Used over a Decade Ago', 'Used over a Decade Ago'), ('Used in Last Decade', 'Used in Last Decade'), ('Used in Last Year', 'Used in Last Year'), ('Used in Last Month', 'Used in Last Month'), ('Used in Last Week', 'Used in Last Week'), ('Used in Last Day', 'Used in Last Day')], max_length=100, null=True)),
                ('crack', models.CharField(blank=True, choices=[('Never Used', 'Never Used'), ('Used over a Decade Ago', 'Used over a Decade Ago'), ('Used in Last Decade', 'Used in Last Decade'), ('Used in Last Year', 'Used in Last Year'), ('Used in Last Month', 'Used in Last Month'), ('Used in Last Week', 'Used in Last Week'), ('Used in Last Day', 'Used in Last Day')], max_length=100, null=True)),
                ('ecstasy', models.CharField(blank=True, choices=[('Never Used', 'Never Used'), ('Used over a Decade Ago', 'Used over a Decade Ago'), ('Used in Last Decade', 'Used in Last Decade'), ('Used in Last Year', 'Used in Last Year'), ('Used in Last Month', 'Used in Last Month'), ('Used in Last Week', 'Used in Last Week'), ('Used in Last Day', 'Used in Last Day')], max_length=100, null=True)),
                ('heroin', models.CharField(blank=True, choices=[('Never Used', 'Never Used'), ('Used over a Decade Ago', 'Used over a Decade Ago'), ('Used in Last Decade', 'Used in Last Decade'), ('Used in Last Year', 'Used in Last Year'), ('Used in Last Month', 'Used in Last Month'), ('Used in Last Week', 'Used in Last Week'), ('Used in Last Day', 'Used in Last Day')], max_length=100, null=True)),
                ('ketamine', models.CharField(blank=True, choices=[('Never Used', 'Never Used'), ('Used over a Decade Ago', 'Used over a Decade Ago'), ('Used in Last Decade', 'Used in Last Decade'), ('Used in Last Year', 'Used in Last Year'), ('Used in Last Month', 'Used in Last Month'), ('Used in Last Week', 'Used in Last Week'), ('Used in Last Day', 'Used in Last Day')], max_length=100, null=True)),
                ('legalh', models.CharField(blank=True, choices=[('Never Used', 'Never Used'), ('Used over a Decade Ago', 'Used over a Decade Ago'), ('Used in Last Decade', 'Used in Last Decade'), ('Used in Last Year', 'Used in Last Year'), ('Used in Last Month', 'Used in Last Month'), ('Used in Last Week', 'Used in Last Week'), ('Used in Last Day', 'Used in Last Day')], max_length=100, null=True)),
                ('lsd', models.CharField(blank=True, choices=[('Never Used', 'Never Used'), ('Used over a Decade Ago', 'Used over a Decade Ago'), ('Used in Last Decade', 'Used in Last Decade'), ('Used in Last Year', 'Used in Last Year'), ('Used in Last Month', 'Used in Last Month'), ('Used in Last Week', 'Used in Last Week'), ('Used in Last Day', 'Used in Last Day')], max_length=100, null=True)),
                ('meth', models.CharField(blank=True, choices=[('Never Used', 'Never Used'), ('Used over a Decade Ago', 'Used over a Decade Ago'), ('Used in Last Decade', 'Used in Last Decade'), ('Used in Last Year', 'Used in Last Year'), ('Used in Last Month', 'Used in Last Month'), ('Used in Last Week', 'Used in Last Week'), ('Used in Last Day', 'Used in Last Day')], max_length=100, null=True)),
                ('mushrooms', models.CharField(blank=True, choices=[('Never Used', 'Never Used'), ('Used over a Decade Ago', 'Used over a Decade Ago'), ('Used in Last Decade', 'Used in Last Decade'), ('Used in Last Year', 'Used in Last Year'), ('Used in Last Month', 'Used in Last Month'), ('Used in Last Week', 'Used in Last Week'), ('Used in Last Day', 'Used in Last Day')], max_length=100, null=True)),
                ('nicotine', models.CharField(blank=True, choices=[('Never Used', 'Never Used'), ('Used over a Decade Ago', 'Used over a Decade Ago'), ('Used in Last Decade', 'Used in Last Decade'), ('Used in Last Year', 'Used in Last Year'), ('Used in Last Month', 'Used in Last Month'), ('Used in Last Week', 'Used in Last Week'), ('Used in Last Day', 'Used in Last Day')], max_length=100, null=True)),
                ('vsa', models.CharField(blank=True, choices=[('Never Used', 'Never Used'), ('Used over a Decade Ago', 'Used over a Decade Ago'), ('Used in Last Decade', 'Used in Last Decade'), ('Used in Last Year', 'Used in Last Year'), ('Used in Last Month', 'Used in Last Month'), ('Used in Last Week', 'Used in Last Week'), ('Used in Last Day', 'Used in Last Day')], max_length=100, null=True)),
                ('semer', models.CharField(blank=True, choices=[('Never Used', 'Never Used'), ('Used over a Decade Ago', 'Used over a Decade Ago'), ('Used in Last Decade', 'Used in Last Decade'), ('Used in Last Year', 'Used in Last Year'), ('Used in Last Month', 'Used in Last Month'), ('Used in Last Week', 'Used in Last Week'), ('Used in Last Day', 'Used in Last Day')], max_length=100, null=True)),
            ],
        ),
    ]
