# Generated by Django 5.0.3 on 2024-04-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correlation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personality_trait', models.CharField(blank=True, max_length=100, null=True)),
                ('drug', models.CharField(blank=True, choices=[('alcohol', 'alcohol'), ('amphet', 'amphet'), ('amyl', 'amyl'), ('benzos', 'benzos'), ('caff', 'caff'), ('cannabis', 'cannabis'), ('choc', 'choc'), ('coke', 'coke'), ('crack', 'crack'), ('ecstasy', 'ecstasy'), ('heroin', 'heroin'), ('ketamine', 'ketamine'), ('legalh', 'legalh'), ('lsd', 'lsd'), ('meth', 'meth'), ('mushrooms', 'mushrooms'), ('nicotine', 'nicotine'), ('semer', 'semer'), ('vsa', 'vsa')], max_length=100, null=True)),
                ('correlation', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
