# Generated by Django 5.0.3 on 2024-04-07 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("endpoints", "0002_correlation"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Correlation",
            new_name="CorrelationToDrug",
        ),
    ]
