# Generated by Django 5.0.3 on 2024-04-10 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("endpoints", "0003_rename_correlation_correlationmatrix"),
    ]

    operations = [
        migrations.RenameField(
            model_name="CorrelationToDrug",
            old_name="personality_trait",
            new_name="feature",
        ),
    ]
