# Generated by Django 5.0.3 on 2024-04-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0004_rename_personality_trait_correlationmodel_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeanCorrelationToFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(blank=True, max_length=100, null=True)),
                ('mean_correlation', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
